title: Pranav Prakash
description: My Bio
theme: just-the-docs

url: https://pranavmyname.github.io

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# aux_links:
#   Template Repository: https://github.com/pranavmyname/just-the-docs-template
